export const competitorProfilesData = [
  {
    company_name: 'Grab Holdings',
    brand_names: ['Grab', 'GrabFood', 'GrabCar', 'GrabPay'],
    country: 'Singapore',
    countries_operated: ['Singapore', 'Malaysia', 'Thailand', 'Indonesia', 'Philippines', 'Vietnam'],
    industry: 'Technology',
    sub_sectors: ['Ride-hailing', 'Food Delivery', 'Digital Payments', 'Logistics'],
    market_share_percentage: 45.5,
    annual_revenue_usd: 2100000000,
    employee_count: 9800,
    entry_year: 2012,
    headquarters_location: 'Singapore',
    business_model: 'Super-app platform connecting drivers, delivery partners, and merchants with consumers',
    competitive_advantages: ['First-mover advantage', 'Strong regional presence', 'Ecosystem integration', 'Local market knowledge'],
    weaknesses: ['Profitability challenges', 'Regulatory scrutiny', 'Driver retention'],
    expansion_plans: 'Expanding financial services and digital banking across SEA',
    parent_company: 'Grab Holdings Limited',
    stock_symbol: 'GRAB',
    website: 'https://www.grab.com',
    data_sources: ['Company filings', 'Market research reports'],
    confidence_score: 95
  },
  {
    company_name: 'Gojek',
    brand_names: ['Gojek', 'GoFood', 'GoPay', 'GoRide'],
    country: 'Indonesia',
    countries_operated: ['Indonesia', 'Singapore', 'Thailand', 'Vietnam'],
    industry: 'Technology',
    sub_sectors: ['Ride-hailing', 'Food Delivery', 'Digital Payments', 'Logistics'],
    market_share_percentage: 35.2,
    annual_revenue_usd: 1800000000,
    employee_count: 7500,
    entry_year: 2010,
    headquarters_location: 'Jakarta, Indonesia',
    business_model: 'Multi-service platform offering transportation, delivery, and payment solutions',
    competitive_advantages: ['Strong Indonesian market presence', 'Local partnerships', 'Diverse service offerings'],
    weaknesses: ['Geographic concentration', 'Intense competition', 'Profitability concerns'],
    expansion_plans: 'Merger with Tokopedia to form GoTo Group, focusing on e-commerce integration',
    parent_company: 'GoTo Group',
    stock_symbol: 'GOTO',
    website: 'https://www.gojek.com',
    data_sources: ['Company announcements', 'Industry reports'],
    confidence_score: 92
  },
  {
    company_name: 'Shopee',
    brand_names: ['Shopee', 'ShopeePay', 'Shopee Food'],
    country: 'Singapore',
    countries_operated: ['Singapore', 'Malaysia', 'Thailand', 'Indonesia', 'Philippines', 'Vietnam'],
    industry: 'Technology',
    sub_sectors: ['E-commerce', 'Digital Payments', 'Logistics'],
    market_share_percentage: 52.3,
    annual_revenue_usd: 7600000000,
    employee_count: 15000,
    entry_year: 2015,
    headquarters_location: 'Singapore',
    business_model: 'C2C and B2C e-commerce marketplace with integrated payments and logistics',
    competitive_advantages: ['Market leadership', 'Strong financial backing', 'Gaming-based engagement', 'Free shipping programs'],
    weaknesses: ['High cash burn', 'Seller disputes', 'Counterfeit concerns'],
    expansion_plans: 'Expanding into financial services and cross-border e-commerce',
    parent_company: 'Sea Limited',
    stock_symbol: 'SE',
    website: 'https://www.shopee.com',
    data_sources: ['Q3 2024 earnings report', 'Market analysis'],
    confidence_score: 97
  },
  {
    company_name: 'Lazada',
    brand_names: ['Lazada', 'RedMart'],
    country: 'Singapore',
    countries_operated: ['Singapore', 'Malaysia', 'Thailand', 'Indonesia', 'Philippines', 'Vietnam'],
    industry: 'Technology',
    sub_sectors: ['E-commerce', 'Logistics'],
    market_share_percentage: 28.7,
    annual_revenue_usd: 4200000000,
    employee_count: 12000,
    entry_year: 2012,
    headquarters_location: 'Singapore',
    business_model: 'B2C and marketplace e-commerce platform with logistics infrastructure',
    competitive_advantages: ['Alibaba backing', 'Strong logistics network', 'Brand recognition'],
    weaknesses: ['Market share loss to Shopee', 'Profitability challenges'],
    expansion_plans: 'Integration with Alibaba ecosystem and cross-border commerce',
    parent_company: 'Alibaba Group',
    stock_symbol: 'BABA',
    website: 'https://www.lazada.com',
    data_sources: ['Company reports', 'Industry analysis'],
    confidence_score: 90
  },
  {
    company_name: 'Sea Limited (Garena)',
    brand_names: ['Garena', 'Free Fire', 'Shopee', 'SeaMoney'],
    country: 'Singapore',
    countries_operated: ['Singapore', 'Malaysia', 'Thailand', 'Indonesia', 'Philippines', 'Vietnam'],
    industry: 'Technology',
    sub_sectors: ['Gaming', 'E-commerce', 'Digital Financial Services'],
    market_share_percentage: 65.8,
    annual_revenue_usd: 13200000000,
    employee_count: 67000,
    entry_year: 2009,
    headquarters_location: 'Singapore',
    business_model: 'Diversified technology conglomerate with gaming, e-commerce, and fintech',
    competitive_advantages: ['Vertical integration', 'Gaming revenue funding e-commerce', 'Regional dominance'],
    weaknesses: ['Gaming regulation risks', 'High operating costs'],
    expansion_plans: 'Expanding digital financial services and seeking profitability',
    parent_company: 'Sea Limited',
    stock_symbol: 'SE',
    website: 'https://www.sea.com',
    data_sources: ['Public filings', 'Investor presentations'],
    confidence_score: 98
  }
];

export const competitorActivitiesData = [
  {
    company_name: 'Grab Holdings',
    activity_type: 'funding',
    activity_title: 'Raised $300M in Series H Funding',
    description: 'Secured additional funding to expand financial services and strengthen market position across Southeast Asia',
    country: 'Singapore',
    industry: 'Technology',
    investment_amount_usd: 300000000,
    impact_level: 'High',
    strategic_significance: 'Demonstrates investor confidence and provides capital for expansion',
    activity_date: '2024-09-15',
    data_sources: ['TechCrunch', 'Company announcement'],
    tags: ['funding', 'fintech', 'expansion']
  },
  {
    company_name: 'Shopee',
    activity_type: 'product_launch',
    activity_title: 'Launched Shopee Premium Membership',
    description: 'Introduced subscription-based premium membership with free shipping and exclusive deals',
    country: 'Singapore',
    industry: 'Technology',
    investment_amount_usd: 0,
    impact_level: 'Medium',
    strategic_significance: 'Creates recurring revenue stream and improves customer loyalty',
    activity_date: '2024-10-01',
    data_sources: ['Company blog', 'Press release'],
    tags: ['product launch', 'subscription', 'customer retention']
  },
  {
    company_name: 'Gojek',
    activity_type: 'merger',
    activity_title: 'Completed Merger with Tokopedia',
    description: 'Finalized merger to form GoTo Group, creating Indonesia\'s largest tech company',
    country: 'Indonesia',
    industry: 'Technology',
    investment_amount_usd: 0,
    impact_level: 'High',
    strategic_significance: 'Creates super-app ecosystem combining ride-hailing, e-commerce, and payments',
    activity_date: '2024-08-20',
    data_sources: ['Bloomberg', 'Reuters'],
    tags: ['merger', 'consolidation', 'ecosystem']
  },
  {
    company_name: 'Lazada',
    activity_type: 'expansion',
    activity_title: 'Opened New Fulfillment Center in Vietnam',
    description: 'Launched state-of-the-art 50,000 sqm fulfillment center to improve delivery times',
    country: 'Vietnam',
    industry: 'Technology',
    investment_amount_usd: 75000000,
    impact_level: 'Medium',
    strategic_significance: 'Strengthens logistics capabilities in fast-growing Vietnamese market',
    activity_date: '2024-11-05',
    data_sources: ['Vietnam News', 'Company announcement'],
    tags: ['expansion', 'logistics', 'infrastructure']
  }
];

export const marketShareData = [
  {
    country: 'Singapore',
    industry: 'Technology',
    sub_sector: 'Ride-hailing',
    company_name: 'Grab',
    market_share_percentage: 72.5,
    rank: 1,
    revenue_usd: 580000000,
    year: 2024,
    quarter: 3,
    total_market_size_usd: 800000000,
    growth_rate: 8.5,
    data_source: 'Market Research Firm',
    methodology: 'Based on gross bookings and transaction volume'
  },
  {
    country: 'Singapore',
    industry: 'Technology',
    sub_sector: 'E-commerce',
    company_name: 'Shopee',
    market_share_percentage: 58.3,
    rank: 1,
    revenue_usd: 2100000000,
    year: 2024,
    quarter: 3,
    total_market_size_usd: 3600000000,
    growth_rate: 12.3,
    data_source: 'Industry Analysis',
    methodology: 'Based on GMV and active users'
  },
  {
    country: 'Indonesia',
    industry: 'Technology',
    sub_sector: 'Ride-hailing',
    company_name: 'Gojek',
    market_share_percentage: 52.8,
    rank: 1,
    revenue_usd: 950000000,
    year: 2024,
    quarter: 3,
    total_market_size_usd: 1800000000,
    growth_rate: 15.7,
    data_source: 'Market Research',
    methodology: 'Transaction volume analysis'
  },
  {
    country: 'Thailand',
    industry: 'Technology',
    sub_sector: 'Food Delivery',
    company_name: 'Grab',
    market_share_percentage: 48.2,
    rank: 1,
    revenue_usd: 420000000,
    year: 2024,
    quarter: 3,
    total_market_size_usd: 870000000,
    growth_rate: 22.1,
    data_source: 'Industry Report',
    methodology: 'Order volume and merchant partnerships'
  }
];

export const pricingIntelligenceData = [
  {
    company_name: 'Grab',
    product_name: 'GrabCar Economy',
    product_category: 'Ride-hailing',
    country: 'Singapore',
    city: 'Singapore',
    price_local_currency: 8.50,
    currency_code: 'SGD',
    price_usd: 6.30,
    pricing_model: 'per-trip',
    price_tier: 'economy',
    features_included: ['Basic car', 'Standard driver', 'In-app payment'],
    competitor_comparison: [{ competitor: 'Gojek', price_diff: '-5%' }],
    price_positioning: 'value',
    discounts_available: '20% off first 3 rides for new users',
    observation_date: '2024-11-10',
    data_source: 'App price check'
  },
  {
    company_name: 'Shopee',
    product_name: 'Shopee Premium',
    product_category: 'E-commerce Subscription',
    country: 'Singapore',
    city: 'Singapore',
    price_local_currency: 4.99,
    currency_code: 'SGD',
    price_usd: 3.69,
    pricing_model: 'subscription',
    price_tier: 'premium',
    features_included: ['Free shipping', 'Exclusive deals', 'Priority support'],
    competitor_comparison: [{ competitor: 'Lazada', price_diff: '+15%' }],
    price_positioning: 'mid-range',
    discounts_available: 'First month free',
    observation_date: '2024-11-12',
    data_source: 'App subscription page'
  }
];

export const marketEntryBarriersData = [
  {
    country: 'Singapore',
    industry: 'Technology',
    barrier_type: 'financial',
    barrier_title: 'High Operating Costs',
    description: 'Singapore has one of the highest costs of doing business in Asia, with expensive office space, high salaries, and significant regulatory compliance costs',
    severity_level: 'High',
    estimated_cost_usd: 500000,
    time_to_overcome_days: 180,
    mitigation_strategies: ['Start with remote team', 'Use co-working spaces', 'Hire selectively', 'Consider regional headquarters model'],
    examples: ['Startups typically need $500K-$1M runway for first year operations'],
    regulatory_reference: 'Enterprise Singapore guidelines'
  },
  {
    country: 'Indonesia',
    industry: 'Technology',
    barrier_type: 'regulatory',
    barrier_title: 'Local Ownership Requirements',
    description: 'Indonesia requires majority local ownership for certain business categories, particularly in e-commerce and digital services',
    severity_level: 'High',
    estimated_cost_usd: 0,
    time_to_overcome_days: 365,
    mitigation_strategies: ['Form joint venture with local partner', 'Use nominee shareholders (with caution)', 'Apply for special exemptions'],
    examples: ['E-commerce companies must have local partnerships', 'Payment processors need Indonesian majority ownership'],
    regulatory_reference: 'Presidential Regulation No. 10/2021'
  },
  {
    country: 'Thailand',
    industry: 'Retail',
    barrier_type: 'cultural',
    barrier_title: 'Language and Cultural Adaptation',
    description: 'Thai consumers prefer localized experiences with Thai language support and culturally appropriate marketing',
    severity_level: 'Medium',
    estimated_cost_usd: 150000,
    time_to_overcome_days: 90,
    mitigation_strategies: ['Hire local marketing team', 'Invest in Thai localization', 'Partner with local influencers', 'Study local consumer behavior'],
    examples: ['International brands that succeeded adapted marketing and product offerings significantly'],
    regulatory_reference: 'N/A'
  }
];
