export const salaryBenchmarksData = [
  {
    country: 'Singapore',
    city: 'Singapore',
    job_title: 'Software Engineer',
    job_level: 'Mid-Level',
    industry: 'Technology',
    min_salary_usd: 48000,
    max_salary_usd: 85000,
    median_salary_usd: 66000,
    currency_code: 'SGD',
    experience_years_min: 3,
    experience_years_max: 7,
    typical_benefits: ['Annual bonus', 'Stock options', 'Health insurance', 'Annual leave 14-21 days'],
    salary_growth_rate: 6.5,
    demand_level: 'High',
    skills_required: ['JavaScript', 'React', 'Node.js', 'AWS', 'Agile'],
    data_source: 'Salary surveys 2024',
    sample_size: 450,
    last_updated: '2024-10-01'
  },
  {
    country: 'Singapore',
    job_title: 'Marketing Manager',
    job_level: 'Senior',
    industry: 'Marketing',
    min_salary_usd: 60000,
    max_salary_usd: 105000,
    median_salary_usd: 82000,
    currency_code: 'SGD',
    experience_years_min: 5,
    experience_years_max: 10,
    typical_benefits: ['Performance bonus', 'Car allowance', 'Health insurance', 'Annual leave 18-21 days'],
    salary_growth_rate: 5.2,
    demand_level: 'Medium',
    skills_required: ['Digital marketing', 'Brand management', 'Analytics', 'Leadership'],
    data_source: 'Industry reports',
    sample_size: 320,
    last_updated: '2024-10-01'
  },
  {
    country: 'Thailand',
    job_title: 'Software Engineer',
    job_level: 'Mid-Level',
    industry: 'Technology',
    min_salary_usd: 18000,
    max_salary_usd: 36000,
    median_salary_usd: 27000,
    currency_code: 'THB',
    experience_years_min: 3,
    experience_years_max: 7,
    typical_benefits: ['Annual bonus 1-3 months', 'Health insurance', 'Social security', 'Annual leave 10-15 days'],
    salary_growth_rate: 8.5,
    demand_level: 'High',
    skills_required: ['JavaScript', 'Python', 'React', 'Mobile development'],
    data_source: 'JobsDB Thailand',
    sample_size: 280,
    last_updated: '2024-09-15'
  },
  {
    country: 'Malaysia',
    job_title: 'Financial Analyst',
    job_level: 'Mid-Level',
    industry: 'Finance',
    min_salary_usd: 15000,
    max_salary_usd: 28000,
    median_salary_usd: 21000,
    currency_code: 'MYR',
    experience_years_min: 3,
    experience_years_max: 6,
    typical_benefits: ['Annual bonus', 'EPF/SOCSO', 'Medical benefits', 'Annual leave 12-16 days'],
    salary_growth_rate: 5.8,
    demand_level: 'Medium',
    skills_required: ['Financial modeling', 'Excel', 'SQL', 'Reporting'],
    data_source: 'Salary Guide Malaysia',
    sample_size: 190,
    last_updated: '2024-09-01'
  },
  {
    country: 'Indonesia',
    job_title: 'Software Engineer',
    job_level: 'Mid-Level',
    industry: 'Technology',
    min_salary_usd: 12000,
    max_salary_usd: 24000,
    median_salary_usd: 18000,
    currency_code: 'IDR',
    experience_years_min: 3,
    experience_years_max: 7,
    typical_benefits: ['THR bonus', 'BPJS health', 'Annual leave 12 days', 'Transport allowance'],
    salary_growth_rate: 9.2,
    demand_level: 'Very High',
    skills_required: ['Java', 'Go', 'Microservices', 'Cloud platforms'],
    data_source: 'Tech in Asia Salary Report',
    sample_size: 520,
    last_updated: '2024-10-10'
  },
  {
    country: 'Philippines',
    job_title: 'Customer Service Representative',
    job_level: 'Entry-Level',
    industry: 'BPO',
    min_salary_usd: 4200,
    max_salary_usd: 7200,
    median_salary_usd: 5700,
    currency_code: 'PHP',
    experience_years_min: 0,
    experience_years_max: 2,
    typical_benefits: ['Night differential', 'HMO', 'SSS/PhilHealth/Pag-IBIG', 'Performance bonus'],
    salary_growth_rate: 6.8,
    demand_level: 'High',
    skills_required: ['English fluency', 'Communication', 'Computer literacy', 'Customer service'],
    data_source: 'BPO Industry Survey',
    sample_size: 750,
    last_updated: '2024-08-20'
  },
  {
    country: 'Vietnam',
    job_title: 'Software Engineer',
    job_level: 'Mid-Level',
    industry: 'Technology',
    min_salary_usd: 15000,
    max_salary_usd: 30000,
    median_salary_usd: 22000,
    currency_code: 'VND',
    experience_years_min: 3,
    experience_years_max: 7,
    typical_benefits: ['13th month salary', 'Social insurance', 'Health insurance', 'Annual leave 12 days'],
    salary_growth_rate: 10.5,
    demand_level: 'Very High',
    skills_required: ['Java', 'JavaScript', 'React', 'DevOps', 'English'],
    data_source: 'VietnamWorks Salary Survey',
    sample_size: 410,
    last_updated: '2024-09-25'
  }
];

export const laborMarketStatsData = [
  {
    country: 'Singapore',
    year: 2024,
    quarter: 3,
    labor_force_size: 3800000,
    employment_rate: 98.0,
    unemployment_rate: 2.0,
    youth_unemployment_rate: 5.2,
    labor_force_participation_rate: 68.5,
    average_monthly_wage_usd: 4200,
    wage_growth_yoy: 5.4,
    key_growth_sectors: ['Technology', 'Financial Services', 'Healthcare', 'Professional Services'],
    skills_shortage_areas: ['Cybersecurity', 'Data Science', 'Cloud Architecture', 'AI/ML'],
    foreign_worker_percentage: 38.0,
    aging_workforce_concerns: 'High - median age increasing',
    data_source: 'Ministry of Manpower Singapore',
    notes: 'Strong talent market with high demand for tech skills'
  },
  {
    country: 'Thailand',
    year: 2024,
    quarter: 3,
    labor_force_size: 39500000,
    employment_rate: 98.9,
    unemployment_rate: 1.1,
    youth_unemployment_rate: 3.8,
    labor_force_participation_rate: 67.2,
    average_monthly_wage_usd: 580,
    wage_growth_yoy: 3.2,
    key_growth_sectors: ['Tourism', 'Manufacturing', 'Technology', 'Agriculture'],
    skills_shortage_areas: ['Digital skills', 'Engineering', 'Healthcare professionals'],
    foreign_worker_percentage: 5.5,
    aging_workforce_concerns: 'Medium - gradual aging',
    data_source: 'National Statistical Office Thailand',
    notes: 'Low unemployment but skills mismatch in tech sector'
  },
  {
    country: 'Malaysia',
    year: 2024,
    quarter: 3,
    labor_force_size: 16800000,
    employment_rate: 96.7,
    unemployment_rate: 3.3,
    youth_unemployment_rate: 9.5,
    labor_force_participation_rate: 69.8,
    average_monthly_wage_usd: 780,
    wage_growth_yoy: 4.1,
    key_growth_sectors: ['E&E Manufacturing', 'Technology', 'Services', 'Healthcare'],
    skills_shortage_areas: ['Software development', 'Data analytics', 'Automation', 'Green technology'],
    foreign_worker_percentage: 15.0,
    aging_workforce_concerns: 'Medium - aging population',
    data_source: 'Department of Statistics Malaysia',
    notes: 'Youth unemployment higher than national average'
  },
  {
    country: 'Indonesia',
    year: 2024,
    quarter: 3,
    labor_force_size: 144500000,
    employment_rate: 94.2,
    unemployment_rate: 5.8,
    youth_unemployment_rate: 16.8,
    labor_force_participation_rate: 69.4,
    average_monthly_wage_usd: 320,
    wage_growth_yoy: 6.8,
    key_growth_sectors: ['Technology', 'Manufacturing', 'Retail', 'Construction'],
    skills_shortage_areas: ['Tech skills', 'Management', 'English proficiency', 'Specialized trades'],
    foreign_worker_percentage: 0.1,
    aging_workforce_concerns: 'Low - young population',
    data_source: 'Statistics Indonesia (BPS)',
    notes: 'Large workforce with significant youth unemployment challenges'
  }
];

export const recruitmentPartnersData = [
  {
    partner_name: 'Robert Walters Singapore',
    partner_type: 'Executive Search',
    country: 'Singapore',
    cities_served: ['Singapore'],
    specializations: ['Finance', 'Technology', 'Legal', 'Operations'],
    service_offerings: ['Executive search', 'Contract staffing', 'Salary surveys', 'Market intelligence'],
    typical_fee_percentage: 20,
    placement_guarantee_days: 90,
    average_time_to_fill_days: 45,
    success_rate: 92,
    min_salary_range_usd: 50000,
    contact_email: 'singapore@robertwalters.com',
    contact_phone: '+65-6228-1888',
    website: 'https://www.robertwalters.com.sg',
    languages_supported: ['English', 'Mandarin'],
    rating: 4.5
  },
  {
    partner_name: 'Monroe Consulting Group Thailand',
    partner_type: 'Executive Search',
    country: 'Thailand',
    cities_served: ['Bangkok', 'Chiang Mai', 'Phuket'],
    specializations: ['General Management', 'Sales', 'Technology', 'Manufacturing'],
    service_offerings: ['Executive search', 'Mid-level recruitment', 'Market mapping', 'Compensation analysis'],
    typical_fee_percentage: 18,
    placement_guarantee_days: 90,
    average_time_to_fill_days: 60,
    success_rate: 88,
    min_salary_range_usd: 30000,
    contact_email: 'thailand@monroeconsulting.com',
    contact_phone: '+66-2-611-7330',
    website: 'https://www.monroeconsulting.com',
    languages_supported: ['English', 'Thai'],
    rating: 4.3
  },
  {
    partner_name: 'Glints Indonesia',
    partner_type: 'Tech Recruitment Platform',
    country: 'Indonesia',
    cities_served: ['Jakarta', 'Bandung', 'Surabaya', 'Bali'],
    specializations: ['Technology', 'Digital Marketing', 'Product Management', 'Startups'],
    service_offerings: ['Platform access', 'Employer branding', 'Assessment tools', 'ATS integration'],
    typical_fee_percentage: 15,
    placement_guarantee_days: 60,
    average_time_to_fill_days: 30,
    success_rate: 85,
    min_salary_range_usd: 10000,
    contact_email: 'indonesia@glints.com',
    contact_phone: '+62-21-2963-8888',
    website: 'https://www.glints.com',
    languages_supported: ['English', 'Bahasa Indonesia'],
    rating: 4.6
  }
];
