export const commercialPropertiesData = [
  {
    property_id: 'SG-OFF-001',
    property_name: 'Marina Bay Financial Centre Tower 1',
    property_type: 'Office',
    country: 'Singapore',
    city: 'Singapore',
    district: 'Marina Bay',
    address: '8 Marina Boulevard, Singapore 018981',
    total_area_sqm: 45000,
    available_area_sqm: 2500,
    price_per_sqm_usd: 95,
    total_price_usd: 237500,
    listing_type: 'Lease',
    lease_term_months: 36,
    grade: 'Grade A',
    building_age_years: 12,
    amenities: ['24/7 security', 'Underground parking', 'Fitness center', 'Sky garden', 'Conference facilities'],
    transport_connectivity: ['Raffles Place MRT (2 min walk)', 'Multiple bus routes', 'Marina Bay area'],
    nearby_businesses: ['Financial institutions', 'Law firms', 'Tech companies'],
    contact_info: { agent: 'Knight Frank', phone: '+65-6220-0000' },
    listing_status: 'Available'
  },
  {
    property_id: 'TH-OFF-001',
    property_name: 'Empire Tower',
    property_type: 'Office',
    country: 'Thailand',
    city: 'Bangkok',
    district: 'Sathorn',
    address: '195 South Sathorn Road, Bangkok 10120',
    total_area_sqm: 75000,
    available_area_sqm: 5000,
    price_per_sqm_usd: 28,
    total_price_usd: 140000,
    listing_type: 'Lease',
    lease_term_months: 36,
    grade: 'Grade A',
    building_age_years: 28,
    amenities: ['24/7 security', 'Parking', 'Cafeteria', 'Banking services'],
    transport_connectivity: ['BTS Chong Nonsi (8 min walk)', 'Major expressway access'],
    nearby_businesses: ['Embassies', 'Hotels', 'Corporate offices'],
    contact_info: { agent: 'CBRE Thailand', phone: '+66-2-643-8000' },
    listing_status: 'Available'
  },
  {
    property_id: 'MY-OFF-001',
    property_name: 'Menara Maxis',
    property_type: 'Office',
    country: 'Malaysia',
    city: 'Kuala Lumpur',
    district: 'KLCC',
    address: 'Kuala Lumpur City Centre, 50088 Kuala Lumpur',
    total_area_sqm: 58000,
    available_area_sqm: 3200,
    price_per_sqm_usd: 22,
    total_price_usd: 70400,
    listing_type: 'Lease',
    lease_term_months: 36,
    grade: 'Grade A',
    building_age_years: 15,
    amenities: ['Smart building tech', 'Parking', 'Meeting rooms', 'Retail podium'],
    transport_connectivity: ['KLCC LRT station (5 min walk)', 'Bus hub adjacent'],
    nearby_businesses: ['Petronas Twin Towers', 'Luxury retail', 'Hotels'],
    contact_info: { agent: 'Savills Malaysia', phone: '+60-3-2092-5100' },
    listing_status: 'Available'
  },
  {
    property_id: 'ID-WH-001',
    property_name: 'Lippo Cikarang Industrial Estate',
    property_type: 'Warehouse',
    country: 'Indonesia',
    city: 'Bekasi',
    district: 'Cikarang',
    address: 'Jl. Lippo Cikarang, Bekasi, West Java',
    total_area_sqm: 12000,
    available_area_sqm: 12000,
    price_per_sqm_usd: 4.5,
    total_price_usd: 54000,
    listing_type: 'Lease',
    lease_term_months: 60,
    grade: 'Industrial',
    building_age_years: 5,
    amenities: ['Loading docks', 'High ceiling (12m)', 'Security system', '24/7 operations'],
    transport_connectivity: ['Near toll road', '45 min to Jakarta port', 'Truck access'],
    nearby_businesses: ['Manufacturing facilities', 'Logistics companies', 'Distribution centers'],
    contact_info: { agent: 'Colliers Indonesia', phone: '+62-21-2988-0888' },
    listing_status: 'Available'
  }
];

export const economicZonesData = [
  {
    zone_name: 'Jurong Innovation District',
    zone_type: 'Innovation District',
    country: 'Singapore',
    city: 'Singapore',
    total_area_hectares: 600,
    development_status: 'Under Development',
    target_completion_year: 2028,
    focus_industries: ['Advanced Manufacturing', 'Clean Energy', 'Sustainable Urban Solutions'],
    key_features: ['Integrated workspace', 'R&D facilities', 'Green buildings', 'Smart infrastructure'],
    incentives_available: ['R&D tax deductions', 'Pioneer status', 'Land subsidies'],
    major_tenants: ['NTU', 'A*STAR', 'Various startups'],
    connectivity: ['Jurong Region Line', 'Major expressways', 'Tuas Port proximity'],
    investment_required_usd: 15000000000,
    government_agency: 'JTC Corporation',
    website: 'https://www.jtc.gov.sg/about-jtc/jurong-innovation-district'
  },
  {
    zone_name: 'Eastern Economic Corridor (EEC)',
    zone_type: 'Special Economic Zone',
    country: 'Thailand',
    city: 'Rayong/Chonburi',
    total_area_hectares: 1300000,
    development_status: 'Active',
    target_completion_year: 2027,
    focus_industries: ['Automotive', 'Electronics', 'Aviation', 'Robotics', 'Digital'],
    key_features: ['Tax incentives', 'Visa privileges', 'Infrastructure investment', 'Fast-track permits'],
    incentives_available: ['Up to 15-year tax holidays', 'Duty exemptions', 'Foreign ownership allowances'],
    major_tenants: ['BMW', 'Airbus', 'Various automotive manufacturers'],
    connectivity: ['U-Tapao Airport', 'Laem Chabang Port', 'High-speed rail'],
    investment_required_usd: 45000000000,
    government_agency: 'EEC Office',
    website: 'https://www.eeco.or.th'
  },
  {
    zone_name: 'Iskandar Malaysia',
    zone_type: 'Economic Region',
    country: 'Malaysia',
    city: 'Johor Bahru',
    total_area_hectares: 220000,
    development_status: 'Active',
    target_completion_year: 2025,
    focus_industries: ['Healthcare', 'Education', 'Tourism', 'Logistics', 'Creative'],
    key_features: ['Strategic location near Singapore', 'Integrated development', 'Quality infrastructure'],
    incentives_available: ['Tax exemptions', 'Investment allowances', 'Duty-free imports'],
    major_tenants: ['Legoland', 'Newcastle University', 'Various logistics companies'],
    connectivity: ['Senai International Airport', 'Causeway to Singapore', 'Port of Tanjung Pelepas'],
    investment_required_usd: 100000000000,
    government_agency: 'Iskandar Regional Development Authority',
    website: 'https://www.irda.com.my'
  }
];

export const infrastructureProjectsData = [
  {
    project_name: 'Bangkok-Chiang Mai High-Speed Rail',
    project_type: 'Transportation',
    country: 'Thailand',
    status: 'Planning',
    estimated_completion_year: 2030,
    total_investment_usd: 12000000000,
    funding_sources: ['Government budget', 'PPP model', 'Foreign investment'],
    project_scope: 'High-speed rail linking Bangkok to Chiang Mai with stations in major cities',
    economic_impact: 'Significant boost to tourism and regional connectivity',
    business_opportunities: ['Construction', 'Real estate development', 'Hospitality', 'Logistics'],
    implementation_agency: 'State Railway of Thailand',
    environmental_considerations: 'EIA approved, green corridor development',
    reference_url: 'https://www.railway.co.th'
  },
  {
    project_name: 'Jakarta MRT Extension Phase 2',
    project_type: 'Transportation',
    country: 'Indonesia',
    status: 'Under Construction',
    estimated_completion_year: 2027,
    total_investment_usd: 3500000000,
    funding_sources: ['JICA loan', 'Government budget'],
    project_scope: 'Extension of Jakarta MRT from Bundaran HI to Kota, 8 new stations',
    economic_impact: 'Reduced traffic congestion, improved property values along route',
    business_opportunities: ['Station area development', 'Retail', 'Real estate'],
    implementation_agency: 'MRT Jakarta',
    environmental_considerations: 'Underground construction to minimize surface impact',
    reference_url: 'https://www.jakartamrt.co.id'
  },
  {
    project_name: 'Johor Bahru-Singapore RTS Link',
    project_type: 'Transportation',
    country: 'Malaysia',
    status: 'Under Construction',
    estimated_completion_year: 2026,
    total_investment_usd: 2500000000,
    funding_sources: ['Joint Malaysia-Singapore project'],
    project_scope: 'Rapid transit system connecting Johor Bahru and Singapore',
    economic_impact: 'Enhanced cross-border connectivity, property development',
    business_opportunities: ['Property development', 'Retail', 'Services'],
    implementation_agency: 'RTS Link Sdn Bhd',
    environmental_considerations: 'Green transportation alternative',
    reference_url: 'https://www.rtslink.com.my'
  }
];
