export const businessRegistrationData = [
  {
    country: 'Singapore',
    business_entity_type: 'Private Limited Company',
    registration_authority: 'Accounting and Corporate Regulatory Authority (ACRA)',
    registration_process_description: 'Online registration through BizFile+ portal with digital signature',
    required_documents: ['Passport copies of directors', 'Proof of registered address', 'Company constitution', 'Director consent forms'],
    minimum_capital_usd: 1,
    processing_time_days: 1,
    registration_cost_usd: 315,
    annual_compliance_cost_usd: 180,
    foreign_ownership_allowed: true,
    foreign_ownership_percentage: 100,
    local_director_required: true,
    local_shareholder_required: false,
    key_regulations: 'Companies Act, Business Registration Act',
    tax_registration_required: true,
    tax_id_type: 'Unique Entity Number (UEN)',
    online_registration_available: true
  },
  {
    country: 'Malaysia',
    business_entity_type: 'Sdn Bhd',
    registration_authority: 'Companies Commission of Malaysia (SSM)',
    registration_process_description: 'Online or physical registration through SSM portal',
    required_documents: ['IC/Passport copies', 'Proof of registered office', 'Memorandum and Articles of Association', 'Statutory declarations'],
    minimum_capital_usd: 0,
    processing_time_days: 7,
    registration_cost_usd: 1200,
    annual_compliance_cost_usd: 300,
    foreign_ownership_allowed: true,
    foreign_ownership_percentage: 100,
    local_director_required: false,
    local_shareholder_required: false,
    key_regulations: 'Companies Act 2016',
    tax_registration_required: true,
    tax_id_type: 'Tax Identification Number (TIN)',
    online_registration_available: true
  },
  {
    country: 'Thailand',
    business_entity_type: 'Limited Company',
    registration_authority: 'Department of Business Development (DBD)',
    registration_process_description: 'Registration through DBD office with notarized documents',
    required_documents: ['Passport copies', 'Company memorandum', 'Articles of association', 'Shareholder meeting minutes', 'Property lease agreement'],
    minimum_capital_usd: 28000,
    processing_time_days: 14,
    registration_cost_usd: 850,
    annual_compliance_cost_usd: 450,
    foreign_ownership_allowed: true,
    foreign_ownership_percentage: 49,
    local_director_required: true,
    local_shareholder_required: true,
    key_regulations: 'Foreign Business Act B.E. 2542',
    tax_registration_required: true,
    tax_id_type: 'Tax ID',
    online_registration_available: false
  },
  {
    country: 'Indonesia',
    business_entity_type: 'PT PMA (Foreign Investment Company)',
    registration_authority: 'Ministry of Law and Human Rights',
    registration_process_description: 'Multi-step registration through OSS (Online Single Submission) system and notary',
    required_documents: ['Passport copies', 'Company deed', 'Tax registration', 'Business license (NIB)', 'Capital investment plan'],
    minimum_capital_usd: 140000,
    processing_time_days: 30,
    registration_cost_usd: 2500,
    annual_compliance_cost_usd: 850,
    foreign_ownership_allowed: true,
    foreign_ownership_percentage: 100,
    local_director_required: true,
    local_shareholder_required: false,
    key_regulations: 'Investment Law No. 25/2007',
    tax_registration_required: true,
    tax_id_type: 'NPWP',
    online_registration_available: true
  },
  {
    country: 'Philippines',
    business_entity_type: 'Corporation',
    registration_authority: 'Securities and Exchange Commission (SEC)',
    registration_process_description: 'Registration through SEC online portal or physical office',
    required_documents: ['Articles of Incorporation', 'By-laws', 'Treasurer\'s affidavit', 'Bank certificate', 'Valid IDs'],
    minimum_capital_usd: 0,
    processing_time_days: 10,
    registration_cost_usd: 600,
    annual_compliance_cost_usd: 400,
    foreign_ownership_allowed: true,
    foreign_ownership_percentage: 40,
    local_director_required: true,
    local_shareholder_required: true,
    key_regulations: 'Revised Corporation Code',
    tax_registration_required: true,
    tax_id_type: 'TIN',
    online_registration_available: true
  },
  {
    country: 'Vietnam',
    business_entity_type: 'Limited Liability Company',
    registration_authority: 'Department of Planning and Investment',
    registration_process_description: 'Registration through DPI with notarized documents',
    required_documents: ['Passport copies', 'Investment registration certificate', 'Company charter', 'Lease agreement', 'Capital verification'],
    minimum_capital_usd: 0,
    processing_time_days: 21,
    registration_cost_usd: 950,
    annual_compliance_cost_usd: 500,
    foreign_ownership_allowed: true,
    foreign_ownership_percentage: 100,
    local_director_required: true,
    local_shareholder_required: false,
    key_regulations: 'Enterprise Law 2020',
    tax_registration_required: true,
    tax_id_type: 'Tax Code',
    online_registration_available: false
  }
];

export const taxIncentivesData = [
  {
    country: 'Singapore',
    incentive_name: 'Startup Tax Exemption Scheme',
    incentive_type: 'Tax Exemption',
    description: 'Qualifying startups enjoy tax exemption on first SGD 200,000 of normal chargeable income',
    eligibility_criteria: 'New company incorporated in Singapore, maximum 20 shareholders, all individual shareholders',
    benefit_amount_usd: 20000,
    duration_years: 3,
    application_process: 'Automatic qualification, claim during tax filing',
    authority_agency: 'Inland Revenue Authority of Singapore (IRAS)',
    industry_focus: 'All industries',
    size_requirements: 'Startups only',
    reference_url: 'https://www.iras.gov.sg'
  },
  {
    country: 'Thailand',
    incentive_name: 'BOI Investment Promotion',
    incentive_type: 'Corporate Tax Exemption',
    description: 'Up to 8 years corporate income tax exemption for promoted activities',
    eligibility_criteria: 'Investment in promoted industries, minimum investment threshold, employment requirements',
    benefit_amount_usd: 500000,
    duration_years: 8,
    application_process: 'Submit application to BOI with investment plan and feasibility study',
    authority_agency: 'Board of Investment (BOI)',
    industry_focus: 'Technology, Manufacturing, Agriculture, Infrastructure',
    size_requirements: 'Varies by industry',
    reference_url: 'https://www.boi.go.th'
  },
  {
    country: 'Malaysia',
    incentive_name: 'Principal Hub Incentive',
    incentive_type: 'Preferential Tax Rate',
    description: 'Preferential tax rate of 0%, 5% or 10% for qualifying regional headquarters',
    eligibility_criteria: 'Minimum annual business spending, qualifying services, employment requirements',
    benefit_amount_usd: 1000000,
    duration_years: 5,
    application_process: 'Apply through MIDA with business plan',
    authority_agency: 'Malaysian Investment Development Authority (MIDA)',
    industry_focus: 'Regional HQ, Shared Services',
    size_requirements: 'Large corporations',
    reference_url: 'https://www.mida.gov.my'
  },
  {
    country: 'Indonesia',
    incentive_name: 'Tax Holiday',
    incentive_type: 'Corporate Tax Reduction',
    description: '50-100% corporate tax reduction for 5-20 years for pioneer industries',
    eligibility_criteria: 'Minimum investment IDR 100 billion, pioneer industry, high economic impact',
    benefit_amount_usd: 2000000,
    duration_years: 20,
    application_process: 'Submit investment plan to Ministry of Investment',
    authority_agency: 'Ministry of Investment/BKPM',
    industry_focus: 'Manufacturing, Technology, Renewable Energy',
    size_requirements: 'Large investment',
    reference_url: 'https://www.bkpm.go.id'
  }
];

export const regulatoryPolicyData = [
  {
    country: 'Singapore',
    policy_title: 'Personal Data Protection Act Amendment 2024',
    policy_type: 'Data Protection',
    description: 'Enhanced data protection requirements including mandatory data breach notifications',
    effective_date: '2024-10-01',
    impact_level: 'High',
    affected_industries: ['Technology', 'Finance', 'Healthcare', 'Retail'],
    compliance_deadline: '2025-04-01',
    key_requirements: ['Data breach notification within 72 hours', 'Enhanced consent management', 'Data portability rights'],
    penalties_for_noncompliance: 'Up to SGD 1 million or 10% of annual turnover',
    guidance_documents_url: 'https://www.pdpc.gov.sg',
    status: 'Active'
  },
  {
    country: 'Thailand',
    policy_title: 'Foreign Business Act Relaxation',
    policy_type: 'Foreign Investment',
    description: 'Relaxation of foreign ownership restrictions for certain service sectors',
    effective_date: '2024-06-15',
    impact_level: 'High',
    affected_industries: ['Professional Services', 'Technology', 'Education'],
    compliance_deadline: '2024-06-15',
    key_requirements: ['Re-registration for qualifying businesses', 'Minimum investment thresholds', 'Employment quotas'],
    penalties_for_noncompliance: 'Business license revocation',
    guidance_documents_url: 'https://www.dbd.go.th',
    status: 'Active'
  },
  {
    country: 'Indonesia',
    policy_title: 'OSS System Update - NIB Integration',
    policy_type: 'Business Registration',
    description: 'Integration of business licensing into single NIB (Business Identification Number)',
    effective_date: '2024-01-01',
    impact_level: 'Medium',
    affected_industries: ['All Industries'],
    compliance_deadline: '2024-12-31',
    key_requirements: ['Re-register through OSS system', 'Update company data', 'Obtain new NIB'],
    penalties_for_noncompliance: 'Administrative sanctions',
    guidance_documents_url: 'https://oss.go.id',
    status: 'Active'
  }
];
